apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-rhacm-manager
rules:
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies
  - placementbindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placements
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

