apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: ocp-etcd-backup
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: etcd-backup
          restartPolicy: Never
          containers:
            - name: etcd-backup
              image: quay.io/openshift-release-dev/ocp-release:4.14.13-x86_64
              command:
                - /bin/bash
                - -c
                - |
                  oc debug node/$(oc get node -l node-role.kubernetes.io/master --no-headers | awk '{print $1}' | head -n1) -- chroot /host sudo /usr/local/bin/cluster-backup.sh /mnt/nfs/etcd-backups
              volumeMounts:
                - name: nfs
                  mountPath: /mnt/nfs/etcd-backups
          volumes:
            - name: nfs
              persistentVolumeClaim:
                claimName: etcd-backup-pvc

