apiVersion: v1
kind: Namespace
metadata:
  name: ocp-etcd-backup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup
  namespace: ocp-etcd-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-backup
rules:
  - apiGroups: ["*"]
    resources: ["nodes", "pods", "pods/exec"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-backup
subjects:
  - kind: ServiceAccount
    name: etcd-backup
    namespace: ocp-etcd-backup

