apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: bind-self-provisioner
  namespace: acm-policies
placementRef:
  name: self-provisioner-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-remove-self-provisioner
    kind: Policy
    apiGroup: policy.open-cluster-management.io

